// Class automatically generated by Dev-C++ New Class wizard

#ifndef IRUDIKOITALIANREADER_H
#define IRUDIKOITALIANREADER_H

#include <config.h>

#include "irudikogenericreader.h" // inheriting class's header file

using namespace std;

/*
 * Italian language reader for Irudiko
 */
class IrudikoItalianReader : public IrudikoGenericReader
{
	public:
		// class constructor
		IrudikoItalianReader();
		IrudikoItalianReader(bool stemPhase);
		IrudikoItalianReader(bool,IrudikoFileType);
		IrudikoItalianReader(IrudikoFileType);
		// class destructor
		~IrudikoItalianReader();
	protected:
		const char * getStopwordFileName() { return "stopwords_it.txt"; };
		int stem();
};

#endif // IRUDIKOITALIANREADER_H
