// Class automatically generated by Dev-C++ New Class wizard

#ifndef IRUDIKOSIMPLEREADER_H
#define IRUDIKOSIMPLEREADER_H

#include <config.h>

#include "irudikogenericreader.h" // inheriting class's header file

using namespace std;

/*
 * Simple, language-independent, reader for Irudiko
 */
class IrudikoSimpleReader : public IrudikoGenericReader
{
	public:
		// class constructor
		IrudikoSimpleReader();
		IrudikoSimpleReader(bool);
		IrudikoSimpleReader(bool,IrudikoFileType);
		IrudikoSimpleReader(IrudikoFileType);
		// class destructor
		~IrudikoSimpleReader();
	protected:
		const char * getStopwordFileName() { return ""; };
		int stem();
};

#endif // IRUDIKOSIMPLEREADER_H
