// Class automatically generated by Dev-C++ New Class wizard

#ifndef IRUDIKOENGLISHREADER_H
#define IRUDIKOENGLISHREADER_H

#include <config.h>

#include "irudikogenericreader.h" // inheriting class's header file

using namespace std;

/*
 * English language reader for Irudiko
 */
class IrudikoEnglishReader : public IrudikoGenericReader
{
	public:
		// class constructor
		IrudikoEnglishReader();
		IrudikoEnglishReader(bool);
		IrudikoEnglishReader(bool,IrudikoFileType);
		IrudikoEnglishReader(IrudikoFileType);
		// class destructor
		~IrudikoEnglishReader();
	protected:
		const char * getStopwordFileName() { return "stopwords_en.txt"; };
		int stem();
};

#endif // IRUDIKOENGLISHREADER_H
