// Class automatically generated by Dev-C++ New Class wizard

#include "irudikoitalianreader.h" // class's header file
#include "italianstemmer.h"

// class constructor
IrudikoItalianReader::IrudikoItalianReader() : IrudikoGenericReader()
{
}

// class constructor
IrudikoItalianReader::IrudikoItalianReader(bool stemPhase) : IrudikoGenericReader(stemPhase)
{
}

// class constructor
IrudikoItalianReader::IrudikoItalianReader(bool stemPhase, IrudikoFileType _filetype) : IrudikoGenericReader(stemPhase, _filetype)
{
}

// class constructor
IrudikoItalianReader::IrudikoItalianReader(IrudikoFileType _filetype) : IrudikoGenericReader(_filetype)
{
}


IrudikoItalianReader::~IrudikoItalianReader()
{
	// insert your code here
}

int IrudikoItalianReader::stem() {
    char buf[64];
    for (vector<string>::iterator itr=wordlist.begin();itr!=wordlist.end();itr++) {
		string s = (string)*itr;
		s.copy(buf,s.size());
		
    	int res = ItalianStemmer::do_stem(buf, s.size()-1);
    	buf[res+1]='\0';
    	
		string s2(buf,res+1);
    	*itr = s2;
	}
	
	return 0;
}
