// Class automatically generated by Dev-C++ New Class wizard

#include "irudikosimplereader.h" // class's header file
// This version of the reader does not implement by choice any sort of stopword removal or stemming approach
// It should be used just for cases in which the page language is not known/given in advance

// class constructor
IrudikoSimpleReader::IrudikoSimpleReader() : IrudikoGenericReader(false)
{
}

// class constructor
IrudikoSimpleReader::IrudikoSimpleReader(bool stemPhase) : IrudikoGenericReader(false)
{
}

// class constructor
IrudikoSimpleReader::IrudikoSimpleReader(bool stemPhase, IrudikoFileType _filetype) : IrudikoGenericReader(false, _filetype)
{
}

// class constructor
IrudikoSimpleReader::IrudikoSimpleReader(IrudikoFileType _filetype) : IrudikoGenericReader(false, _filetype)
{
}

// class destructor
IrudikoSimpleReader::~IrudikoSimpleReader()
{
	// insert your code here
}

// Stemming phase is not implemented
int IrudikoSimpleReader::stem() {
  return 0;
}
