// Class automatically generated by Dev-C++ New Class wizard

#include "irudikoenglishreader.h" // class's header file
#include "englishstemmer.h"

// class constructor
IrudikoEnglishReader::IrudikoEnglishReader() : IrudikoGenericReader()
{
}

// class constructor
IrudikoEnglishReader::IrudikoEnglishReader(bool stemPhase) : IrudikoGenericReader(stemPhase)
{
}

// class constructor
IrudikoEnglishReader::IrudikoEnglishReader(bool stemPhase, IrudikoFileType _filetype) : IrudikoGenericReader(stemPhase, _filetype)
{
}

// class constructor
IrudikoEnglishReader::IrudikoEnglishReader(IrudikoFileType _filetype) : IrudikoGenericReader(_filetype)
{
}

// class destructor
IrudikoEnglishReader::~IrudikoEnglishReader()
{
	// insert your code here
}

int IrudikoEnglishReader::stem() {
    EnglishStemmer stemmer;
    char buf[64];
    for (vector<string>::iterator itr=wordlist.begin();itr!=wordlist.end();itr++) {
		string s = (string)*itr;
		s.copy(buf,s.size());
		
    	int res = stemmer.do_stem(buf, s.size()-1);
    	buf[res+1]='\0';
    	
		string s2(buf,res+1);
    	*itr = s2;
	}
	
	return 0;
}
